import { CatalogCategory, CatalogItem, CatalogSettings } from '../types';

export const INITIAL_CATEGORIES: CatalogCategory[] = [
  { id: 'cat-general', name: 'General', isSystem: true, createdAt: new Date(Date.now() - 30 * 86400000).toISOString() },
  { id: 'cat-products', name: 'Products & Goods', isSystem: true, createdAt: new Date(Date.now() - 29 * 86400000).toISOString() },
  { id: 'cat-services', name: 'Services & Consulting', isSystem: true, createdAt: new Date(Date.now() - 28 * 86400000).toISOString() },
  { id: 'cat-tech', name: 'Hardware & Accessories', isSystem: false, createdAt: new Date(Date.now() - 20 * 86400000).toISOString() },
  { id: 'cat-apparel', name: 'Merchandise & Apparel', isSystem: false, createdAt: new Date(Date.now() - 15 * 86400000).toISOString() },
];

export const INITIAL_SETTINGS: CatalogSettings & { id: string } = {
  id: 'catalog_settings',
  nextItemCode: 108,
  allowCustomItems: true,
  recentCategories: ['cat-products', 'cat-services', 'cat-tech'],
};

export const INITIAL_ITEMS: CatalogItem[] = [
  {
    id: 'item-101',
    itemCode: 'ITEM-101',
    name: 'Artisanal Whole Espresso Beans 500g',
    type: 'product',
    categoryId: 'cat-products',
    categorySnapshot: 'Products & Goods',
    description: 'Single-origin Arabica roasted locally. Rich chocolate & caramel notes.',
    sku: 'COFF-AR-500',
    barcode: '8901234567891',
    unit: 'bag',
    price: 18.50,
    costPrice: 8.20,
    stockTracked: true,
    stockQty: 24,
    lowStockThreshold: 8,
    taxLabel: 'Standard (10%)',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=400&q=80',
    tags: ['coffee', 'roast', 'bestseller'],
    status: 'active',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'item-102',
    itemCode: 'ITEM-102',
    name: 'Cold Brew Coffee Concentrate 1L',
    type: 'product',
    categoryId: 'cat-products',
    categorySnapshot: 'Products & Goods',
    description: '12-hour slow steeped brew. Yields up to 10 drinks when diluted.',
    sku: 'COFF-CB-1L',
    barcode: '8901234567892',
    unit: 'bottle',
    price: 14.00,
    costPrice: 5.50,
    stockTracked: true,
    stockQty: 3, // LOW STOCK TRIGGER!
    lowStockThreshold: 5,
    taxLabel: 'Standard (10%)',
    tags: ['beverage', 'coldbrew', 'lowstock'],
    status: 'active',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'item-103',
    itemCode: 'ITEM-103',
    name: 'Full Device Diagnostic & Cleaning',
    type: 'service',
    categoryId: 'cat-services',
    categorySnapshot: 'Services & Consulting',
    description: 'Hardware inspection, thermal paste re-application, and internal dust removal.',
    unit: 'session',
    price: 49.00,
    costPrice: 12.00,
    stockTracked: false,
    taxLabel: 'Exempt',
    tags: ['maintenance', 'repair', 'hardware'],
    status: 'active',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'item-104',
    itemCode: 'ITEM-104',
    name: 'Monthly Technical Support Retainer',
    type: 'service',
    categoryId: 'cat-services',
    categorySnapshot: 'Services & Consulting',
    description: 'Dedicated priority support for up to 5 team workstations with 4h SLA.',
    unit: 'month',
    price: 299.00,
    costPrice: 80.00,
    stockTracked: false,
    taxLabel: 'Standard (10%)',
    tags: ['retainer', 'b2b', 'support'],
    status: 'active',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'item-105',
    itemCode: 'ITEM-105',
    name: 'Braided Nylon USB-C Cable 2m 100W',
    type: 'product',
    categoryId: 'cat-tech',
    categorySnapshot: 'Hardware & Accessories',
    description: 'Ultra-durable fast charging power cable with E-Marker chip.',
    sku: 'CABL-USBC-2M',
    barcode: '8901234567895',
    unit: 'pcs',
    price: 19.99,
    costPrice: 7.50,
    stockTracked: true,
    stockQty: 42,
    lowStockThreshold: 10,
    taxLabel: 'Standard (10%)',
    tags: ['accessory', 'cable', 'tech'],
    status: 'active',
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'item-106',
    itemCode: 'ITEM-106',
    name: 'SALTEDHASH Heavyweight Organic T-Shirt',
    type: 'product',
    categoryId: 'cat-apparel',
    categorySnapshot: 'Merchandise & Apparel',
    description: '240 GSM combed cotton crewneck t-shirt with screenprinted brand emblem.',
    sku: 'TSHIRT-BLK-L',
    unit: 'pcs',
    price: 32.00,
    costPrice: 14.00,
    stockTracked: true,
    stockQty: 12,
    lowStockThreshold: 5,
    taxLabel: 'Standard (10%)',
    tags: ['merch', 'apparel'],
    status: 'active',
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'item-107',
    itemCode: 'ITEM-107',
    name: 'Seasonal Specialty Tasting Box (Legacy)',
    type: 'product',
    categoryId: 'cat-products',
    categorySnapshot: 'Products & Goods',
    description: 'Previous season sample box containing limited release roasts.',
    sku: 'BOX-SEASON-01',
    unit: 'box',
    price: 35.00,
    costPrice: 18.00,
    stockTracked: true,
    stockQty: 0,
    lowStockThreshold: 2,
    status: 'archived', // ARCHIVED ITEM EXAMPLE
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  }
];
